name: dsfsdf
description: Generated app dsfsdf
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.9.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  webview_flutter: ^4.4.2
  intl: ^0.19.0
  table_calendar: ^3.0.9
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 