name: generated_app
description: A generated Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  cloud_firestore: ^4.15.9
  webview_flutter: ^4.7.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.2.1
  firebase_storage: ^11.6.10
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 